### PR TITLE
Cleanup package.json, add readme

### PR DESCRIPTION
**Pull request by jonasfj**
Have a look, simple cleanup... + a readme...

IMO, we should disable issues on all these repos and tell people to file in bugzilla under "taskcluster/platform libraries"... I'm not sure where to write that, any suggestion?

### CODE REVIEW

**Comment by jhford** [comment]
I wanted to have a really short name for the module on npm so that package.json files don't get unwieldy.  We don't need the npm name to be the same as the repo name.  What do you think?

**Comment by jonasfj** [comment]
Npm complained to me in another module about repository name...
Try npm install and see if you can get the warning... Otherwise, I don't mind a short name...

**Comment by jhford** [comment]
I didn't have any trouble or any similar error messages when I played around with it recently.

**Comment by jonasfj** [comment]
@jhford, either we rename the package or the repository... I'm okay renaming the repository... It's really just one violation of our `taskcluster-lib-...` naming scheme...

```
[azure-entities]$rm -rf node_modules/ && npm install && npm test
npm WARN deprecated taskcluster-lib-rules@1.0.5: WARNING: This package, but not repository, was renamed to 'tc-rules' for 1.0.6
```

**Comment by jonasfj** [comment]
@jhford sorry this one is on me...

The warning goes away if I use the `tc-rules` package instead of the `taskcluster-lib-rules` package... Makes sense...

**Pull request closed without merging**
