### PR TITLE
add a babel6 config

### PR DESCRIPTION
**Pull request by jhford**

### CODE REVIEW

**Comment by jhford** [comment]
Turns out babel 6 is out and uses a different config system!

**Comment by jonasfj** [comment]
Hmm... Does this work??
I thought the packages had to be prefixed babel-preset-...

**Comment by jonasfj** [comment]
@jhford, I r+ if this works...
but if we can go back to using babel cli tools... then perhaps a `babel-preset-taskcluster` package would be fine...

**Comment by jhford** [comment]
my understanding is that there's special magic for babel-preset-, but that it's not strictly required... it'll be a quick check for whether its there or not.  We still need to have something for eslint and a couple other similar tools.

Also, babel-compile is sort of important for other things, like having package.json:scripts.compile that's <80chars.

**Comment by jonasfj** [comment]
Agree babel-compile is nice.. If we can teach it to use preset then it
would be less obscure...
Den 18. nov. 2015 1.08 AM skrev "John Ford" notifications@github.com:

**Comment by jhford** [comment]
Yelp, it all works works with presets that we put into tc-rules/babel6

**Pull request merged**
